# Generated by Django 4.1.6 on 2023-02-13 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True)),
                ('details', models.CharField(max_length=50)),
                ('rate', models.IntegerField(default=0)),
                ('total_target', models.IntegerField()),
                ('current_donation', models.IntegerField(default=0)),
                ('start_campaign', models.DateField(blank=True, default=datetime.datetime.now)),
                ('end_campaign', models.DateField()),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('selected_at_by_admin', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Projects_pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/Projects/%y/%m/%d')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapp.project')),
            ],
        ),
    ]
