# Generated by Django 4.1.7 on 2023-02-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=20)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsapp.project')),
            ],
        ),
    ]
